language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
  # Used in freedesktop sdk 19.08
  - 1.39.0

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo fmt --all -- --check
